/**
 * Amazon Product Search Extractor
 * Auto-generated by Manus on 2026-01-31
 *
 * Usage:
 *   import { extract } from './amazon-product-search';
 *   const data = await extract(page);
 */
import type { Page } from 'playwright';

export interface AmazonProductSearchData {
  title: string;
  price: string;
}

export const config = {
  name: 'Amazon Product Search',
  urlPattern: /amazon.com/,
  selectors: {
    container: '[data-component-type=\'s-search-result\']',
    title: '[data-cy=\'title-recipe-title\']',
    price: '.a-price-whole',
  },
};

/**
 * Extract data from the page
 */
export async function extract(page: Page): Promise<AmazonProductSearchData[]> {
  const items = await page.$$(config.selectors.container);

  const data: AmazonProductSearchData[] = [];
  for (const item of items) {
    try {
      data.push({
      title: await item.$eval('[data-cy=\'title-recipe-title\']', el => el.textContent?.trim() ?? ''),
      price: await item.$eval('.a-price-whole', el => el.textContent?.trim() ?? ''),
      });
    } catch (error) {
      console.warn('Failed to extract item:', error);
    }
  }

  return data;
}

/**
 * Check if a URL matches this extractor's pattern
 */
export function matches(url: string): boolean {
  return config.urlPattern.test(url);
}

/**
 * Validate extracted data
 */
export function validate(data: AmazonProductSearchData[]): { valid: boolean; issues: string[] } {
  const issues: string[] = [];

  if (data.length === 0) {
    issues.push('No data extracted');
  }

  data.forEach((item, index) => {
    const emptyFields = Object.entries(item)
      .filter(([_, value]) => !value || String(value).trim() === '')
      .map(([key]) => key);

    if (emptyFields.length > 0) {
      issues.push(`Row ${index + 1}: empty fields - ${emptyFields.join(', ')}`);
    }
  });

  return {
    valid: issues.length === 0,
    issues,
  };
}
