/**
 * Dick's Sporting Goods Product Extractor
 * Auto-generated by Manus on 2026-01-31
 *
 * Usage:
 *   import { extract } from './dicks-sporting-goods-product';
 *   const data = await extract(page);
 */
import type { Page } from 'playwright';

export interface DicksSportingGoodsProductData {
  name: string;
  price: string;
  color: string;
  rating: string;
  brand: string;
  description: string;
}

export const config = {
  name: 'Dick\'s Sporting Goods Product',
  urlPattern: /dickssportinggoods.com/,
  selectors: {
    container: 'body',
    name: 'h1',
    price: '[data-testid=\'product-price\']',
    color: '[data-testid=\'color-name\']',
    rating: '[data-testid=\'bv-rating\']',
    brand: '[data-testid=\'brand-name\']',
    description: '[data-testid=\'product-description\']',
  },
};

/**
 * Extract data from the page
 */
export async function extract(page: Page): Promise<DicksSportingGoodsProductData[]> {
  const items = await page.$$(config.selectors.container);

  const data: DicksSportingGoodsProductData[] = [];
  for (const item of items) {
    try {
      data.push({
      name: await item.$eval('h1', el => el.textContent?.trim() ?? ''),
      price: await item.$eval('[data-testid=\'product-price\']', el => el.textContent?.trim() ?? ''),
      color: await item.$eval('[data-testid=\'color-name\']', el => el.textContent?.trim() ?? ''),
      rating: await item.$eval('[data-testid=\'bv-rating\']', el => el.textContent?.trim() ?? ''),
      brand: await item.$eval('[data-testid=\'brand-name\']', el => el.textContent?.trim() ?? ''),
      description: await item.$eval('[data-testid=\'product-description\']', el => el.textContent?.trim() ?? ''),
      });
    } catch (error) {
      console.warn('Failed to extract item:', error);
    }
  }

  return data;
}

/**
 * Check if a URL matches this extractor's pattern
 */
export function matches(url: string): boolean {
  return config.urlPattern.test(url);
}

/**
 * Validate extracted data
 */
export function validate(data: DicksSportingGoodsProductData[]): { valid: boolean; issues: string[] } {
  const issues: string[] = [];

  if (data.length === 0) {
    issues.push('No data extracted');
  }

  data.forEach((item, index) => {
    const emptyFields = Object.entries(item)
      .filter(([_, value]) => !value || String(value).trim() === '')
      .map(([key]) => key);

    if (emptyFields.length > 0) {
      issues.push(`Row ${index + 1}: empty fields - ${emptyFields.join(', ')}`);
    }
  });

  return {
    valid: issues.length === 0,
    issues,
  };
}
