/**
 * PChome 24h RTX 5090 Laptops Extractor
 * Auto-generated by Manus on 2026-01-31
 *
 * Usage:
 *   import { extract } from './pchome-24h-rtx-5090-laptops';
 *   const data = await extract(page);
 */
import type { Page } from 'playwright';

export interface Pchome24hRtx5090LaptopsData {
  name: string;
  price: string;
  processor: string;
  graphics: string;
  ram: string;
  storage: string;
}

export const config = {
  name: 'PChome 24h RTX 5090 Laptops',
  urlPattern: /24h.pchome.com.tw/,
  selectors: {
    container: 'body',
    name: '.product-title, .product-name',
    price: '.price, .current-price',
    processor: '.spec-processor, .cpu-info',
    graphics: '.gpu-info, .graphics-card',
    ram: '.memory-info, .ram-spec',
    storage: '.storage-info, .disk-spec',
  },
};

/**
 * Extract data from the page
 */
export async function extract(page: Page): Promise<Pchome24hRtx5090LaptopsData[]> {
  const items = await page.$$(config.selectors.container);

  const data: Pchome24hRtx5090LaptopsData[] = [];
  for (const item of items) {
    try {
      data.push({
      name: await item.$eval('.product-title, .product-name', el => el.textContent?.trim() ?? ''),
      price: await item.$eval('.price, .current-price', el => el.textContent?.trim() ?? ''),
      processor: await item.$eval('.spec-processor, .cpu-info', el => el.textContent?.trim() ?? ''),
      graphics: await item.$eval('.gpu-info, .graphics-card', el => el.textContent?.trim() ?? ''),
      ram: await item.$eval('.memory-info, .ram-spec', el => el.textContent?.trim() ?? ''),
      storage: await item.$eval('.storage-info, .disk-spec', el => el.textContent?.trim() ?? ''),
      });
    } catch (error) {
      console.warn('Failed to extract item:', error);
    }
  }

  return data;
}

/**
 * Check if a URL matches this extractor's pattern
 */
export function matches(url: string): boolean {
  return config.urlPattern.test(url);
}

/**
 * Validate extracted data
 */
export function validate(data: Pchome24hRtx5090LaptopsData[]): { valid: boolean; issues: string[] } {
  const issues: string[] = [];

  if (data.length === 0) {
    issues.push('No data extracted');
  }

  data.forEach((item, index) => {
    const emptyFields = Object.entries(item)
      .filter(([_, value]) => !value || String(value).trim() === '')
      .map(([key]) => key);

    if (emptyFields.length > 0) {
      issues.push(`Row ${index + 1}: empty fields - ${emptyFields.join(', ')}`);
    }
  });

  return {
    valid: issues.length === 0,
    issues,
  };
}
