/**
 * Vuori Clothing Product Extractor
 * Auto-generated by Manus on 2026-01-31
 *
 * Usage:
 *   import { extract } from './vuori-clothing-product';
 *   const data = await extract(page);
 */
import type { Page } from 'playwright';

export interface VuoriClothingProductData {
  name: string;
  price: string;
  colors: string;
  sizes: string;
  important_info: string;
}

export const config = {
  name: 'Vuori Clothing Product',
  urlPattern: /vuoriclothing.com/,
  selectors: {
    container: 'body',
    name: 'h1',
    price: '[data-testid=\'price\']',
    colors: '[data-color]',
    sizes: '[data-size]',
    important_info: '.product-description',
  },
};

/**
 * Extract data from the page
 */
export async function extract(page: Page): Promise<VuoriClothingProductData[]> {
  const items = await page.$$(config.selectors.container);

  const data: VuoriClothingProductData[] = [];
  for (const item of items) {
    try {
      data.push({
      name: await item.$eval('h1', el => el.textContent?.trim() ?? ''),
      price: await item.$eval('[data-testid=\'price\']', el => el.textContent?.trim() ?? ''),
      colors: await item.$eval('[data-color]', el => el.textContent?.trim() ?? ''),
      sizes: await item.$eval('[data-size]', el => el.textContent?.trim() ?? ''),
      important_info: await item.$eval('.product-description', el => el.textContent?.trim() ?? ''),
      });
    } catch (error) {
      console.warn('Failed to extract item:', error);
    }
  }

  return data;
}

/**
 * Check if a URL matches this extractor's pattern
 */
export function matches(url: string): boolean {
  return config.urlPattern.test(url);
}

/**
 * Validate extracted data
 */
export function validate(data: VuoriClothingProductData[]): { valid: boolean; issues: string[] } {
  const issues: string[] = [];

  if (data.length === 0) {
    issues.push('No data extracted');
  }

  data.forEach((item, index) => {
    const emptyFields = Object.entries(item)
      .filter(([_, value]) => !value || String(value).trim() === '')
      .map(([key]) => key);

    if (emptyFields.length > 0) {
      issues.push(`Row ${index + 1}: empty fields - ${emptyFields.join(', ')}`);
    }
  });

  return {
    valid: issues.length === 0,
    issues,
  };
}
